import { build as bundle } from 'esbuild';
import { build as vite } from 'vite';
import { mkdir, writeFile, readdir, readFile, copyFile, rm } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
await mkdir('build', { recursive: true });
await rm('build/runner.mjs', { force: true });
await rm('build/runner.mjs.map', { force: true });
await vite();
await bundle({ entryPoints: ['server/index.ts'], outfile: 'build/server.mjs', bundle: true, platform: 'node', format: 'esm', target: 'node22', packages: 'external', sourcemap: true });
await bundle({ entryPoints: ['runner/tools.ts'], outfile: 'build/tools.mjs', bundle: true, platform: 'node', format: 'esm', target: 'node22' });
const assets = (await readdir('build/public/assets')).map(file => `/assets/${file}`);
const version = assets.filter(file => file.endsWith('.js')).join('|');
const cacheName = `garnet-shell-${gzipSync(version).toString('hex').slice(-24)}`;
await writeFile('build/public/sw.js', `const CACHE=${JSON.stringify(cacheName)};const ASSETS=${JSON.stringify(['/', '/index.html', '/manifest.webmanifest', ...assets])};
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>(key.startsWith('ed-shell-')||key.startsWith('garnet-shell-'))&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{const url=new URL(event.request.url);if(event.request.method!=='GET'||url.origin!==self.location.origin||url.pathname.startsWith('/api/')||url.pathname==='/collaboration')return;if(event.request.mode==='navigate'){event.respondWith(fetch(event.request).catch(()=>caches.match('/index.html')));return;}event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request)));});`);
await writeFile('build/public/manifest.webmanifest', JSON.stringify({ name: 'Garnet', short_name: 'Garnet', start_url: '/', display: 'standalone', background_color: '#fdfdfb', theme_color: '#f5f5f1', icons: [] }));
await copyFile('package.json', 'build/package.json');
await copyFile('package-lock.json', 'build/package-lock.json');
const sizes = [];
for (const file of assets.filter(f => f.endsWith('.js'))) sizes.push({ file, gzipBytes: gzipSync(await readFile(`build/public${file}`)).length });
await writeFile('build/bundle-sizes.json', JSON.stringify(sizes, null, 2));
console.log('Gzipped JavaScript:', sizes);
